-- Table des disciplines olympiques (RM-02 : nom unique, insensible à la casse).
CREATE TABLE discipline (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_discipline PRIMARY KEY (id)
);

-- Unicité insensible à la casse (cohérente avec existsByNameIgnoreCase côté service).
CREATE UNIQUE INDEX uk_discipline_name ON discipline (lower(name));
