-- Référentiel des nations (RM-01 : code ISO alpha-3 unique, libellé unique).
CREATE TABLE country (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code       VARCHAR(3)   NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_country PRIMARY KEY (id),
    CONSTRAINT ck_country_code CHECK (code ~ '^[A-Z]{3}$')
);

CREATE UNIQUE INDEX uk_country_code ON country (code);
CREATE UNIQUE INDEX uk_country_name ON country (lower(name));

-- Données de référence (nations) : ensemble extensible, nécessaire aussi en production.
INSERT INTO country (code, name) VALUES
    ('FRA', 'France'),
    ('USA', 'États-Unis'),
    ('GBR', 'Royaume-Uni'),
    ('GER', 'Allemagne'),
    ('ITA', 'Italie'),
    ('ESP', 'Espagne'),
    ('CHN', 'Chine'),
    ('JPN', 'Japon'),
    ('CAN', 'Canada'),
    ('BRA', 'Brésil'),
    ('AUS', 'Australie'),
    ('NED', 'Pays-Bas'),
    ('SEN', 'Sénégal'),
    ('MAR', 'Maroc'),
    ('CIV', 'Côte d''Ivoire'),
    ('KEN', 'Kenya'),
    ('JAM', 'Jamaïque'),
    ('RSA', 'Afrique du Sud'),
    ('NGR', 'Nigéria'),
    ('EGY', 'Égypte'),
    ('KOR', 'Corée du Sud'),
    ('IND', 'Inde'),
    ('MEX', 'Mexique'),
    ('ARG', 'Argentine'),
    ('SUI', 'Suisse'),
    ('BEL', 'Belgique'),
    ('POR', 'Portugal'),
    ('SWE', 'Suède'),
    ('NOR', 'Norvège'),
    ('POL', 'Pologne');
