-- Athlètes (individuels). RM-03/04/05 : nation + discipline existantes, naissance passée, bornes.
CREATE TABLE athlete (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    last_name     VARCHAR(100) NOT NULL,
    first_name    VARCHAR(100) NOT NULL,
    gender        VARCHAR(10)  NOT NULL,
    birth_date    DATE         NOT NULL,
    country_id    BIGINT       NOT NULL,
    discipline_id BIGINT       NOT NULL,
    height_cm     INT          NOT NULL,
    weight_kg     INT          NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_athlete PRIMARY KEY (id),
    CONSTRAINT fk_athlete_country FOREIGN KEY (country_id)
        REFERENCES country (id) ON DELETE RESTRICT,
    CONSTRAINT fk_athlete_discipline FOREIGN KEY (discipline_id)
        REFERENCES discipline (id) ON DELETE RESTRICT,
    CONSTRAINT ck_athlete_gender     CHECK (gender IN ('MALE', 'FEMALE')),
    CONSTRAINT ck_athlete_birth_date CHECK (birth_date < CURRENT_DATE),
    CONSTRAINT ck_athlete_height     CHECK (height_cm BETWEEN 100 AND 260),
    CONSTRAINT ck_athlete_weight     CHECK (weight_kg BETWEEN 30 AND 250)
);

CREATE INDEX ix_athlete_country    ON athlete (country_id);
CREATE INDEX ix_athlete_discipline ON athlete (discipline_id);
CREATE INDEX ix_athlete_last_name  ON athlete (last_name);
CREATE INDEX ix_athlete_gender     ON athlete (gender);
