-- Épreuves (individuelles) rattachées à une discipline. RM-06/07.
CREATE TABLE epreuve (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    label         VARCHAR(150) NOT NULL,
    discipline_id BIGINT       NOT NULL,
    event_date    DATE         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_epreuve PRIMARY KEY (id),
    CONSTRAINT fk_epreuve_discipline FOREIGN KEY (discipline_id)
        REFERENCES discipline (id) ON DELETE RESTRICT
);

-- Unicité d'une épreuve : (libellé insensible à la casse, discipline, date) — RM-07.
CREATE UNIQUE INDEX uk_epreuve_label_discipline_date
    ON epreuve (lower(label), discipline_id, event_date);

CREATE INDEX ix_epreuve_discipline ON epreuve (discipline_id);
CREATE INDEX ix_epreuve_event_date ON epreuve (event_date);
