-- Résultats d'une épreuve : rang d'un athlète et médaille dérivée. RM-08/10/11/12.
CREATE TABLE resultat (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    epreuve_id    BIGINT      NOT NULL,
    athlete_id    BIGINT      NOT NULL,
    rank_position INT         NOT NULL,
    medal         VARCHAR(10),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_resultat PRIMARY KEY (id),
    CONSTRAINT fk_resultat_epreuve FOREIGN KEY (epreuve_id)
        REFERENCES epreuve (id) ON DELETE RESTRICT,
    CONSTRAINT fk_resultat_athlete FOREIGN KEY (athlete_id)
        REFERENCES athlete (id) ON DELETE RESTRICT,
    CONSTRAINT uk_resultat_epreuve_athlete UNIQUE (epreuve_id, athlete_id),
    CONSTRAINT uk_resultat_epreuve_rank    UNIQUE (epreuve_id, rank_position),
    CONSTRAINT ck_resultat_rank  CHECK (rank_position >= 1),
    CONSTRAINT ck_resultat_medal CHECK (medal IN ('OR', 'ARGENT', 'BRONZE')),
    -- RM-12 : la médaille DOIT correspondre au rang (garantie ultime en base).
    CONSTRAINT ck_resultat_rank_medal CHECK (
           (rank_position = 1 AND medal = 'OR')
        OR (rank_position = 2 AND medal = 'ARGENT')
        OR (rank_position = 3 AND medal = 'BRONZE')
        OR (rank_position >= 4 AND medal IS NULL)
    )
);

CREATE INDEX ix_resultat_epreuve ON resultat (epreuve_id);
CREATE INDEX ix_resultat_athlete ON resultat (athlete_id);
CREATE INDEX ix_resultat_medal   ON resultat (medal);
