-- Comptes administrateurs du back-office (isolés du modèle métier).
CREATE TABLE admin_user (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email                 VARCHAR(180) NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,
    role                  VARCHAR(30)  NOT NULL,
    enabled               BOOLEAN      NOT NULL DEFAULT true,
    failed_login_attempts INT          NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    password_changed_at   TIMESTAMPTZ,
    must_change_password  BOOLEAN      NOT NULL DEFAULT true,
    two_factor_enabled    BOOLEAN      NOT NULL DEFAULT false,
    last_login_at         TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_admin_user PRIMARY KEY (id),
    CONSTRAINT ck_admin_user_role CHECK (role IN ('ROLE_ADMIN', 'ROLE_SUPER_ADMIN'))
);

-- Unicité de l'email insensible à la casse.
CREATE UNIQUE INDEX uk_admin_user_email ON admin_user (lower(email));
