-- Refresh tokens révocables (le JWT d'accès reste stateless et à durée courte).
CREATE TABLE refresh_token (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    admin_id   BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT false,
    ip         VARCHAR(45),
    user_agent VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT fk_refresh_token_admin FOREIGN KEY (admin_id)
        REFERENCES admin_user (id) ON DELETE CASCADE,
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_token_admin ON refresh_token (admin_id);
