-- Journal d'audit des opérations d'administration.
CREATE TABLE admin_log (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    admin_id       BIGINT,
    action         VARCHAR(60) NOT NULL,
    target_type    VARCHAR(60),
    target_id      BIGINT,
    success        BOOLEAN     NOT NULL,
    message        VARCHAR(500),
    ip             VARCHAR(45),
    user_agent     VARCHAR(300),
    correlation_id VARCHAR(36),
    duration_ms    BIGINT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_admin_log PRIMARY KEY (id),
    CONSTRAINT fk_admin_log_admin FOREIGN KEY (admin_id)
        REFERENCES admin_user (id) ON DELETE SET NULL
);

CREATE INDEX ix_admin_log_created_at ON admin_log (created_at);
CREATE INDEX ix_admin_log_action ON admin_log (action);
