-- Jobs d'import asynchrone (source de vérité du cycle de vie).
CREATE TABLE import_job (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    job_type           VARCHAR(30)  NOT NULL,
    format             VARCHAR(10)  NOT NULL,
    mode               VARCHAR(10)  NOT NULL,
    duplicate_strategy VARCHAR(10)  NOT NULL,
    status             VARCHAR(12)  NOT NULL,
    source_file_name   VARCHAR(255) NOT NULL,
    stored_file_path   VARCHAR(500) NOT NULL,
    file_size          BIGINT       NOT NULL,
    content_hash       VARCHAR(64)  NOT NULL,
    total_rows         BIGINT       NOT NULL DEFAULT 0,
    processed_rows     BIGINT       NOT NULL DEFAULT 0,
    imported_rows      BIGINT       NOT NULL DEFAULT 0,
    updated_rows       BIGINT       NOT NULL DEFAULT 0,
    skipped_rows       BIGINT       NOT NULL DEFAULT 0,
    failed_rows        BIGINT       NOT NULL DEFAULT 0,
    progress_percent   INT          NOT NULL DEFAULT 0,
    cancel_requested   BOOLEAN      NOT NULL DEFAULT false,
    error_message      VARCHAR(1000),
    correlation_id     VARCHAR(36)  NOT NULL,
    created_by         BIGINT       NOT NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    started_at         TIMESTAMPTZ,
    finished_at        TIMESTAMPTZ,
    duration_ms        BIGINT,
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_import_job PRIMARY KEY (id),
    CONSTRAINT fk_import_job_admin FOREIGN KEY (created_by)
        REFERENCES admin_user (id) ON DELETE RESTRICT,
    CONSTRAINT ck_import_job_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_import_job_mode CHECK (mode IN ('DRY_RUN', 'COMMIT')),
    CONSTRAINT ck_import_job_strategy CHECK (duplicate_strategy IN ('SKIP', 'UPDATE', 'REJECT')),
    CONSTRAINT ck_import_job_progress CHECK (progress_percent BETWEEN 0 AND 100)
);

CREATE INDEX ix_import_job_status ON import_job (status);
CREATE INDEX ix_import_job_created_at ON import_job (created_at);

-- Détail des lignes rejetées (rapport requêtable).
CREATE TABLE import_job_error (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    import_job_id BIGINT       NOT NULL,
    row_number    BIGINT       NOT NULL,
    column_name   VARCHAR(100),
    raw_value     VARCHAR(500),
    error_code    VARCHAR(60)  NOT NULL,
    message       VARCHAR(500) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_import_job_error PRIMARY KEY (id),
    CONSTRAINT fk_import_job_error_job FOREIGN KEY (import_job_id)
        REFERENCES import_job (id) ON DELETE CASCADE
);

CREATE INDEX ix_import_job_error_job ON import_job_error (import_job_id);

-- Enregistrements créés/mis à jour par un job (compensation / annulation).
CREATE TABLE import_job_record (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    import_job_id BIGINT      NOT NULL,
    entity_type   VARCHAR(30) NOT NULL,
    entity_id     BIGINT      NOT NULL,
    operation     VARCHAR(10) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_import_job_record PRIMARY KEY (id),
    CONSTRAINT fk_import_job_record_job FOREIGN KEY (import_job_id)
        REFERENCES import_job (id) ON DELETE CASCADE,
    CONSTRAINT ck_import_job_record_op CHECK (operation IN ('INSERT', 'UPDATE'))
);

CREATE INDEX ix_import_job_record_job ON import_job_record (import_job_id);
